#!/usr/bin/env ruby
#--
# Color
# Colour management with Ruby
# http://rubyforge.org/projects/color
#   Version 1.4.0
#
# Licensed under a MIT-style licence. See Licence.txt in the main
# distribution for full licensing information.
#
# Copyright (c) 2005 - 2007 Austin Ziegler and Matt Lyon
#
# $Id: test_all.rb 55 2007-02-03 23:29:34Z austin $
#++

$LOAD_PATH.unshift("#{File.dirname(__FILE__)}/../lib") if __FILE__ == $0
require 'test/unit'
require 'color'
require 'color/palette/adobecolor'

module TestColor
  module TestPalette
    class TestAdobeColor < Test::Unit::TestCase
      def setup
        wsc = <<-EOS
AAEASAAAhYXDwykqAAAAADs8sK8AAAAAAADJyQQEBAQAAAAAAAAAAJeXAAAA
AP//ZmYAAAAAAAAAAAAA//8AAAAA//+/vyMkAAAAAMnJ5eX8+wAAAACzs6en
oJ8AAAAAzMvd3d3dAAAAADM0mZkzNAAAAABPUHh4n58AAAAAycny8bq5AAAA
AISDycmEgwAAAADNzejn+/sAAAAAFxgpKnN0AAAAAAAAAAAAAAAAAAD//2Zm
AAAAAAAAAAAzNGZmAAAAAP//AACEgwAAAAAAAGNk3NsAAAAA//8AADM0AAAA
AO/vurkAAAAAAAAAAH1+CAgAAAAAGBhFRq2tAAAAAP///////wAAAADf33R0
FxgAAAAA/f349wECAAAAAIWFnJsODgAAAAAyMn5+vr0AAAAA0tEAADk6AAAA
AJGRmZmOjQAAAABVVk1OSUoAAAAAf4B3eHJyAAAAAKSjtrXIxwAAAAAkJH+A
5uUAAAAAAAAuLpKRAAAAAP//lZUjJAAAAACsqwQEgYEAAAAA1NPd3e3tAAAA
AJqZmpmamQAAAAD29Xd4xMMAAAAAEhKPjzU2AAAAAMzLAAAAAAAAAAA7PDs8
OzwAAAAAdHTDw0NEAAAAAO/v7+/v7wAAAAD+/ezrMDAAAAAA/////zAwAAAA
ABcYd3ixsQAAAAD19eHhzc0AAAAAzMtmZgAAAAAAAN3d7u3//wAAAAD//xIS
//8AAAAAT1Ccm+/vAAAAAHx809MAAAAAAAAAAGZmZmYAAAAAzMvMy8zLAAAA
AHFyq6trbAAAAAD+/e3tt7cAAAAACgqqqf39AAAAAAUGODhrbAAAAADx8fb1
//8AAAAA//9sbBcYAAAAAO3tICAkJAAAAADMy8zLzMsAAAAA7e3r69XVAAAA
ADQ0FhYMDAAAAAD//5qZZmYAAAAAurm6ubq5AAAAAAQELi65uQAAAAAeHpCP
//8AAAACAEgAAIWFw8MpKgAAAAAAEQBUAGUAYwBoAG4AbwByAGEAdABpACAA
RwByAGUAZQBuAAAAADs8sK8AAAAAAAAAEQBUAGUAYwBoAG4AbwByAGEAdABp
ACAARwByAGUAZQBuAAAAAMnJBAQEBAAAAAAADwBUAGUAYwBoAG4AbwByAGEA
dABpACAAUgBlAGQAAAAAAAAAAJeXAAAAAAAQAFQAZQBjAGgAbgBvAHIAYQB0
AGkAIABCAGwAdQBlAAAAAP//ZmYAAAAAAAAAEgBSAFMAUwAgAEIAdQB0AHQA
bwBuACAATwByAGEAbgBnAGUAAAAAAAAAAP//AAAAAAARAGQAZQBsAC4AaQBj
AGkAbwAuAHUAcwAgAEIAbAB1AGUAAAAA//+/vyMkAAAAAAAPAEoAbwB0AHMA
cABvAHQAIABPAHIAYQBuAGcAZQAAAADJyeXl/PsAAAAAAA0ASgBvAHQAcwBw
AG8AdAAgAEIAbAB1AGUAAAAAs7Onp6CfAAAAAAARAFQAZQBjAGgAYwByAHUA
bgBjAGgAIABiAHIAbwB3AG4AAAAAzMvd3d3dAAAAAAAQAFQAZQBjAGgAYwBy
AHUAbgBjAGgAIABBAHEAdQBhAAAAADM0mZkzNAAAAAAACwBOAGkAbgBnACAA
ZwByAGUAZQBuAAAAAE9QeHifnwAAAAAACgBEAGkAZwBnACAAQgBsAHUAZQAA
AADJyfLxurkAAAAAABEARABpAGcAZwAgAEwAaQBnAGgAdAAgAEcAcgBlAGUA
bgAAAACEg8nJhIMAAAAAAA8AQgBhAHMAZQBjAGEAbQBwACAAZwByAGUAZQBu
AAAAAM3N6Of7+wAAAAAADgBCAGEAcwBlAGMAYQBtAHAAIABCAGwAdQBlAAAA
ABcYKSpzdAAAAAAADwBXAG8AcgBkAHAAcgBlAHMAcwAgAEIAbAB1AGUAAAAA
AAAAAAAAAAAAAAAQAFcAbwByAGQAcAByAGUAcwBzACAAQgBsAGEAYwBrAAAA
AP//ZmYAAAAAAAAADwBCAGwAbwBnAGcAZQByACAATwByAGEAbgBnAGUAAAAA
AAAzNGZmAAAAAAANAEIAbABvAGcAZwBlAHIAIABCAGwAdQBlAAAAAP//AACE
gwAAAAAADABGAGwAaQBjAGsAcgAgAFAAaQBuAGsAAAAAAABjZNzbAAAAAAAM
AEYAbABpAGMAawByACAAQgBsAHUAZQAAAAD//wAAMzQAAAAAAAsAWQBhAGgA
bwBvACEAIABSAGUAZAAAAADv77q5AAAAAAAAAA4ARwBvAG8AZwBsAGUAIABZ
AGUAbABsAG8AdwAAAAAAAH1+CAgAAAAAAA0ARwBvAG8AZwBsAGUAIABHAHIA
ZQBlAG4AAAAAGBhFRq2tAAAAAAARAEcAbwBvAGcAbABlACAARABhAHIAawAg
AEIAbAB1AGUAAAAA////////AAAAAAANAEcAbwBvAGcAbABlACAAVwBoAGkA
dABlAAAAAN/fdHQXGAAAAAAADwBGAGkAcgBlAGYAbwB4ACAATwByAGEAbgBn
AGUAAAAA/f349wECAAAAAAAPAEYAaQByAGUAZgBvAHgAIABZAGUAbABsAG8A
dwAAAACFhZybDg4AAAAAAA4AVwByAGkAdABlAGwAeQAgAE8AbABpAHYAZQAA
AAAyMn5+vr0AAAAAAA0AVwByAGkAdABlAGwAeQAgAEIAbAB1AGUAAAAA0tEA
ADk6AAAAAAAMAGwAYQBzAHQALgBmAG0AIABSAGUAZAAAAACRkZmZjo0AAAAA
AA0AbABhAHMAdAAuAGYAbQAgAEcAcgBlAHkAAAAAVVZNTklKAAAAAAARAE0A
ZQBhAHMAdQByAGUAbQBhAHAAIABCAHIAbwB3AG4AAAAAf4B3eHJyAAAAAAAQ
AE0AZQBhAHMAdQByAGUAbQBhAHAAIABHAHIAZQB5AAAAAKSjtrXIxwAAAAAA
CwBNAGUAZQBiAG8AIABCAGwAdQBlAAAAACQkf4Dm5QAAAAAAEQBQAGgAbwB0
AG8AYgB1AGMAawBlAHQAIABCAGwAdQBlAAAAAAAALi6SkQAAAAAAGgBDAGEA
bQBwAGEAaQBnAG4ATQBvAG4AaQB0AG8AcgAgAEQAYQByAGsAIABCAGwAdQBl
AAAAAP//lZUjJAAAAAAAFwBDAGEAbQBwAGEAaQBnAG4ATQBvAG4AaQB0AG8A
cgAgAE8AcgBhAG4AZwBlAAAAAKyrBASBgQAAAAAADQBPAHIAawB1AHQAIABQ
AHUAcgBwAGwAZQAAAADU093d7e0AAAAAAAsATwByAGsAdQB0ACAAQgBsAHUA
ZQAAAACamZqZmpkAAAAAAA8AdABoAGkAbgBrAGYAcgBlAGUAIABHAHIAZQB5
AAAAAPb1d3jEwwAAAAAADwB0AGgAaQBuAGsAZgByAGUAZQAgAFAAaQBuAGsA
AAAAEhKPjzU2AAAAAAAQAFcAYQB5AGYAYQByAGkAbgBnACAARwByAGUAZQBu
AAAAAMzLAAAAAAAAAAAADgBXAGEAeQBmAGEAcgBpAG4AZwAgAFIAZQBkAAAA
ADs8Ozw7PAAAAAAADwBXAGEAeQBmAGEAcgBpAG4AZwAgAEcAcgBlAHkAAAAA
dHTDw0NEAAAAAAALAFIAaQB5AGEAIABHAHIAZQBlAG4AAAAA7+/v7+/vAAAA
AAAKAFIAaQB5AGEAIABHAHIAZQB5AAAAAP797OswMAAAAAAADABSAGkAeQBh
ACAAWQBlAGwAbABvAHcAAAAA/////zAwAAAAAAAPAFcAZQBiAG4AbwB0AGUA
IABZAGUAbABsAG8AdwAAAAAXGHd4sbEAAAAAAA4ATABpAG4AawBlAGQASQBu
ACAAQgBsAHUAZQAAAAD19eHhzc0AAAAAABAATABpAG4AawBlAGQASQBuACAA
UABhAHMAdABlAGwAAAAAzMtmZgAAAAAAAAAQAEwAaQBuAGsAZQBkAEkAbgAg
AE8AcgBhAG4AZwBlAAAAAN3d7u3//wAAAAAADwBTAGUAbgBkAHMAcABhAGMA
ZQAgAEIAbAB1AGUAAAAA//8SEv//AAAAAAALAEYAbABvAGMAawAgAFAAaQBu
AGsAAAAAT1Ccm+/vAAAAAAALAEYAbABvAGMAawAgAEIAbAB1AGUAAAAAfHzT
0wAAAAAAAAAMAEYAbABvAGMAawAgAEcAcgBlAGUAbgAAAAAAAGZmZmYAAAAA
AA8AUwBsAGEAcwBoAGQAbwB0ACAARwByAGUAZQBuAAAAAMzLzMvMywAAAAAA
DgBTAGwAYQBzAGgAZABvAHQAIABHAHIAZQB5AAAAAHFyq6trbAAAAAAADwBO
AGUAdwBzAHYAaQBuAGUAIABHAHIAZQBlAG4AAAAA/v3t7be3AAAAAAAMAHcA
aQBuAGsAIABQAGEAcwB0AGUAbAAAAAAKCqqp/f0AAAAAABoAVABoAGkAcwAg
AGIAbAB1AGUAIABpAHMAIABpAG4AIAAoAGIAZQB0AGEAKQAgADoAKQAAAAAF
Bjg4a2wAAAAAAA8AdwBpAG4AawAgAEQAYQByAGsAIABCAGwAdQBlAAAAAPHx
9vX//wAAAAAAEABGAHUAcgBsACAATABpAGcAaAB0ACAAQgBsAHUAZQAAAAD/
/2xsFxgAAAAAAAwARgB1AHIAbAAgAE8AcgBhAG4AZwBlAAAAAO3tICAkJAAA
AAAACgBXAGkAcgBlAGQAIABSAGUAZAAAAADMy8zLzMsAAAAAAAsAVwBpAHIA
ZQBkACAARwByAGUAeQAAAADt7evr1dUAAAAAABMAQQAgAEwAaQBzAHQAIABB
AHAAYQByAHQAIABDAHIAZQBhAG0AAAAANDQWFgwMAAAAAAARAG0AYQAuAGcA
bgBvAGwAaQBhACAATQBhAHIAbwBvAG4AAAAA//+amWZmAAAAAAAPAG0AYQAu
AGcAbgBvAGwAaQBhACAAUABpAG4AawAAAAC6ubq5urkAAAAAAA8AVwBpAGsA
aQBwAGUAZABpAGEAIABHAHIAZQB5AAAAAAQELi65uQAAAAAADwBXAGkAawBp
AHAAZQBkAGkAYQAgAEIAbAB1AGUAAAAAHh6Qj///AAAAAAA+AEgAZQB5ACwA
IABjAG8AbQBlACAAYQBuAGQAIAB2AGkAcwBpAHQAIABtAHkAIABiAGwAbwBn
ACEAIAB+ACAAaAB0AHQAcAA6AC8ALwBtAGkAbABlAHMALgBiAHUAcgBrAGUA
LgBpAGQALgBhAHUALwBiAGwAbwBnAC8AAA==
        EOS
        @adobecolor = Color::Palette::AdobeColor.new(wsc.unpack("m*")[0])
      end

      def test_each
        assert_equal(72, @adobecolor.size)
        @adobecolor.each { |el| assert_kind_of(Color::RGB, el) }
      end

      def test_each_name
        if @adobecolor.version == 1
          assert_equal(0, @adobecolor.instance_variable_get(:@names).size)
        else
          @adobecolor.each_name { |color_name, color_set|
            assert_kind_of(Array, color_set)
            color_set.each { |el|
              assert_kind_of(Color::RGB, el)
            }
          }
        end
      end

      def test_index
        assert_equal("#85c329", @adobecolor[0].html)
      end
    end
  end
end
