#!/usr/bin/env ruby
#--
# Colour management with Ruby.
#
# Copyright 2005 Austin Ziegler
#   http://rubyforge.org/ruby-pdf/
#
#   Licensed under a MIT-style licence.
#
# $Id: metaconfig 153 2007-02-07 02:28:41Z austin $
#++
# vim: sts=2 sw=2 ts=4 et ai tw=77

