# frozen_string_literal: true

require "color"

class Color::RGB
  __create_named_color(self, from_values(0xf0, 0xf8, 0xff), :AliceBlue)
  __create_named_color(self, from_values(0xfa, 0xeb, 0xd7), :AntiqueWhite)
  __create_named_color(self, from_values(0x00, 0xff, 0xff), :Aqua)
  __create_named_color(self, from_values(0x7f, 0xff, 0xd4), :Aquamarine)
  __create_named_color(self, from_values(0xf0, 0xff, 0xff), :Azure)
  __create_named_color(self, from_values(0xf5, 0xf5, 0xdc), :Beige)
  __create_named_color(self, from_values(0xff, 0xe4, 0xc4), :Bisque)
  __create_named_color(self, from_values(0x00, 0x00, 0x00), :Black)
  __create_named_color(self, from_values(0xff, 0xeb, 0xcd), :BlanchedAlmond)
  __create_named_color(self, from_values(0x00, 0x00, 0xff), :Blue)
  __create_named_color(self, from_values(0x8a, 0x2b, 0xe2), :BlueViolet)
  __create_named_color(self, from_values(0xa5, 0x2a, 0x2a), :Brown)
  __create_named_color(self, from_values(0xde, 0xb8, 0x87), :BurlyWood, :Burlywood)
  __create_named_color(self, from_values(0x5f, 0x9e, 0xa0), :CadetBlue)
  __create_named_color(self, from_values(0xff, 0x5e, 0xd0), :Carnation)
  __create_named_color(self, from_values(0x8d, 0x00, 0x00), :Cayenne)
  __create_named_color(self, from_values(0x7f, 0xff, 0x00), :Chartreuse)
  __create_named_color(self, from_values(0xd2, 0x69, 0x1e), :Chocolate)
  __create_named_color(self, from_values(0xff, 0x7f, 0x50), :Coral)
  __create_named_color(self, from_values(0x64, 0x95, 0xed), :CornflowerBlue)
  __create_named_color(self, from_values(0xff, 0xf8, 0xdc), :Cornsilk)
  __create_named_color(self, from_values(0xdc, 0x14, 0x3c), :Crimson)
  __create_named_color(self, from_values(0x00, 0xff, 0xff), :Cyan)
  __create_named_color(self, from_values(0x00, 0x00, 0x8b), :DarkBlue)
  __create_named_color(self, from_values(0x00, 0x8b, 0x8b), :DarkCyan)
  __create_named_color(self, from_values(0xb8, 0x86, 0x0b), :DarkGoldenRod, :DarkGoldenrod)
  __create_named_color(self, from_values(0xa9, 0xa9, 0xa9), :DarkGray, :DarkGrey)
  __create_named_color(self, from_values(0x00, 0x64, 0x00), :DarkGreen)
  __create_named_color(self, from_values(0xbd, 0xb7, 0x6b), :DarkKhaki)
  __create_named_color(self, from_values(0x8b, 0x00, 0x8b), :DarkMagenta)
  __create_named_color(self, from_values(0x55, 0x6b, 0x2f), :DarkOliveGreen, :DarkoliveGreen)
  __create_named_color(self, from_values(0xff, 0x8c, 0x00), :DarkOrange, :Darkorange)
  __create_named_color(self, from_values(0x99, 0x32, 0xcc), :DarkOrchid)
  __create_named_color(self, from_values(0x8b, 0x00, 0x00), :DarkRed)
  __create_named_color(self, from_values(0xe9, 0x96, 0x7a), :DarkSalmon, :Darksalmon)
  __create_named_color(self, from_values(0x8f, 0xbc, 0x8f), :DarkSeaGreen)
  __create_named_color(self, from_values(0x48, 0x3d, 0x8b), :DarkSlateBlue)
  __create_named_color(self, from_values(0x2f, 0x4f, 0x4f), :DarkSlateGray, :DarkSlateGrey)
  __create_named_color(self, from_values(0x00, 0xce, 0xd1), :DarkTurquoise)
  __create_named_color(self, from_values(0x94, 0x00, 0xd3), :DarkViolet)
  __create_named_color(self, from_values(0xff, 0x14, 0x93), :DeepPink)
  __create_named_color(self, from_values(0x00, 0xbf, 0xff), :DeepSkyBlue)
  __create_named_color(self, from_values(0x69, 0x69, 0x69), :DimGray, :DimGrey)
  __create_named_color(self, from_values(0x1e, 0x90, 0xff), :DodgerBlue)
  __create_named_color(self, from_values(0xd1, 0x92, 0x75), :Feldspar)
  __create_named_color(self, from_values(0xb2, 0x22, 0x22), :FireBrick, :Firebrick)
  __create_named_color(self, from_values(0xff, 0xfa, 0xf0), :FloralWhite)
  __create_named_color(self, from_values(0x22, 0x8b, 0x22), :ForestGreen)
  __create_named_color(self, from_values(0xff, 0x00, 0xff), :Fuchsia)
  __create_named_color(self, from_values(0xdc, 0xdc, 0xdc), :Gainsboro)
  __create_named_color(self, from_values(0xf8, 0xf8, 0xff), :GhostWhite)
  __create_named_color(self, from_values(0xff, 0xd7, 0x00), :Gold)
  __create_named_color(self, from_values(0xda, 0xa5, 0x20), :GoldenRod, :Goldenrod)
  __create_named_color(self, from_values(0x80, 0x80, 0x80), :Gray, :Grey)

  __create_named_color(self, from_fraction(0.05, 0.05, 0.05), :Gray05, :Gray5, :Grey05, :Grey5)

  (10..95).step(5) do
    v = _1 / 100.0
    __create_named_color(self, from_fraction(v, v, v), :"Gray#{_1}", :"Grey#{_1}")
  end

  __create_named_color(self, from_values(0x00, 0x80, 0x00), :Green)
  __create_named_color(self, from_values(0xad, 0xff, 0x2f), :GreenYellow)
  __create_named_color(self, from_values(0xf0, 0xff, 0xf0), :HoneyDew, :Honeydew)
  __create_named_color(self, from_values(0xff, 0x69, 0xb4), :HotPink)
  __create_named_color(self, from_values(0xcd, 0x5c, 0x5c), :IndianRed)
  __create_named_color(self, from_values(0x4b, 0x00, 0x82), :Indigo)
  __create_named_color(self, from_values(0xff, 0xff, 0xf0), :Ivory)
  __create_named_color(self, from_values(0xf0, 0xe6, 0x8c), :Khaki)
  __create_named_color(self, from_values(0xe6, 0xe6, 0xfa), :Lavender)
  __create_named_color(self, from_values(0xff, 0xf0, 0xf5), :LavenderBlush)
  __create_named_color(self, from_values(0x7c, 0xfc, 0x00), :LawnGreen)
  __create_named_color(self, from_values(0xff, 0xfa, 0xcd), :LemonChiffon)
  __create_named_color(self, from_values(0xad, 0xd8, 0xe6), :LightBlue)
  __create_named_color(self, from_values(0xf0, 0x80, 0x80), :LightCoral)
  __create_named_color(self, from_values(0xe0, 0xff, 0xff), :LightCyan)
  __create_named_color(self, from_values(0xfa, 0xfa, 0xd2), :LightGoldenRodYellow, :LightGoldenrodYellow)
  __create_named_color(self, from_values(0xd3, 0xd3, 0xd3), :LightGray, :LightGrey)
  __create_named_color(self, from_values(0x90, 0xee, 0x90), :LightGreen)
  __create_named_color(self, from_values(0xff, 0xb6, 0xc1), :LightPink)
  __create_named_color(self, from_values(0xff, 0xa0, 0x7a), :LightSalmon, :Lightsalmon)
  __create_named_color(self, from_values(0x20, 0xb2, 0xaa), :LightSeaGreen)
  __create_named_color(self, from_values(0x87, 0xce, 0xfa), :LightSkyBlue)
  __create_named_color(self, from_values(0x84, 0x70, 0xff), :LightSlateBlue)
  __create_named_color(self, from_values(0x77, 0x88, 0x99), :LightSlateGray, :LightSlateGrey)
  __create_named_color(self, from_values(0xb0, 0xc4, 0xde), :LightSteelBlue, :LightsteelBlue)
  __create_named_color(self, from_values(0xff, 0xff, 0xe0), :LightYellow)
  __create_named_color(self, from_values(0x00, 0xff, 0x00), :Lime)
  __create_named_color(self, from_values(0x32, 0xcd, 0x32), :LimeGreen)
  __create_named_color(self, from_values(0xfa, 0xf0, 0xe6), :Linen)
  __create_named_color(self, from_values(0xff, 0x00, 0xff), :Magenta)
  __create_named_color(self, from_values(0x80, 0x00, 0x00), :Maroon)
  __create_named_color(self, from_values(0x66, 0xcd, 0xaa), :MediumAquaMarine, :MediumAquamarine)
  __create_named_color(self, from_values(0x00, 0x00, 0xcd), :MediumBlue)
  __create_named_color(self, from_values(0xba, 0x55, 0xd3), :MediumOrchid)
  __create_named_color(self, from_values(0x93, 0x70, 0xdb), :MediumPurple)
  __create_named_color(self, from_values(0x3c, 0xb3, 0x71), :MediumSeaGreen)
  __create_named_color(self, from_values(0x7b, 0x68, 0xee), :MediumSlateBlue)
  __create_named_color(self, from_values(0x00, 0xfa, 0x9a), :MediumSpringGreen)
  __create_named_color(self, from_values(0x48, 0xd1, 0xcc), :MediumTurquoise)
  __create_named_color(self, from_values(0xc7, 0x15, 0x85), :MediumVioletRed)
  __create_named_color(self, from_values(0x19, 0x19, 0x70), :MidnightBlue)
  __create_named_color(self, from_values(0xf5, 0xff, 0xfa), :MintCream)
  __create_named_color(self, from_values(0xff, 0xe4, 0xe1), :MistyRose)
  __create_named_color(self, from_values(0xff, 0xe4, 0xb5), :Moccasin)
  __create_named_color(self, from_values(0xff, 0xde, 0xad), :NavajoWhite)
  __create_named_color(self, from_values(0x00, 0x00, 0x80), :Navy)
  __create_named_color(self, from_values(0xfd, 0xf5, 0xe6), :OldLace)
  __create_named_color(self, from_values(0x80, 0x80, 0x00), :Olive)
  __create_named_color(self, from_values(0x6b, 0x8e, 0x23), :OliveDrab, :Olivedrab)
  __create_named_color(self, from_values(0xff, 0xa5, 0x00), :Orange)
  __create_named_color(self, from_values(0xff, 0x45, 0x00), :OrangeRed)
  __create_named_color(self, from_values(0xda, 0x70, 0xd6), :Orchid)
  __create_named_color(self, from_values(0xee, 0xe8, 0xaa), :PaleGoldenRod, :PaleGoldenrod)
  __create_named_color(self, from_values(0x98, 0xfb, 0x98), :PaleGreen)
  __create_named_color(self, from_values(0xaf, 0xee, 0xee), :PaleTurquoise)
  __create_named_color(self, from_values(0xdb, 0x70, 0x93), :PaleVioletRed)
  __create_named_color(self, from_values(0xff, 0xef, 0xd5), :PapayaWhip)
  __create_named_color(self, from_values(0xff, 0xda, 0xb9), :PeachPuff, :Peachpuff)
  __create_named_color(self, from_values(0xcd, 0x85, 0x3f), :Peru)
  __create_named_color(self, from_values(0xff, 0xc0, 0xcb), :Pink)
  __create_named_color(self, from_values(0xdd, 0xa0, 0xdd), :Plum)
  __create_named_color(self, from_values(0xb0, 0xe0, 0xe6), :PowderBlue)
  __create_named_color(self, from_values(0x80, 0x00, 0x80), :Purple)
  __create_named_color(self, from_values(0x66, 0x33, 0x99), :RebeccaPurple)
  __create_named_color(self, from_values(0xff, 0x00, 0x00), :Red)
  __create_named_color(self, from_values(0xbc, 0x8f, 0x8f), :RosyBrown)
  __create_named_color(self, from_values(0x41, 0x69, 0xe1), :RoyalBlue)
  __create_named_color(self, from_values(0x8b, 0x45, 0x13), :SaddleBrown)
  __create_named_color(self, from_values(0xfa, 0x80, 0x72), :Salmon)
  __create_named_color(self, from_values(0xf4, 0xa4, 0x60), :SandyBrown)
  __create_named_color(self, from_values(0x2e, 0x8b, 0x57), :SeaGreen)
  __create_named_color(self, from_values(0xff, 0xf5, 0xee), :SeaShell, :Seashell)
  __create_named_color(self, from_values(0xa0, 0x52, 0x2d), :Sienna)
  __create_named_color(self, from_values(0xc0, 0xc0, 0xc0), :Silver)
  __create_named_color(self, from_values(0x87, 0xce, 0xeb), :SkyBlue)
  __create_named_color(self, from_values(0x6a, 0x5a, 0xcd), :SlateBlue)
  __create_named_color(self, from_values(0x70, 0x80, 0x90), :SlateGray, :SlateGrey)
  __create_named_color(self, from_values(0xff, 0xfa, 0xfa), :Snow)
  __create_named_color(self, from_values(0x00, 0xff, 0x7f), :SpringGreen)
  __create_named_color(self, from_values(0x46, 0x82, 0xb4), :SteelBlue)
  __create_named_color(self, from_values(0xd2, 0xb4, 0x8c), :Tan)
  __create_named_color(self, from_values(0x00, 0x80, 0x80), :Teal)
  __create_named_color(self, from_values(0xd8, 0xbf, 0xd8), :Thistle)
  __create_named_color(self, from_values(0xff, 0x63, 0x47), :Tomato)
  __create_named_color(self, from_values(0x40, 0xe0, 0xd0), :Turquoise)
  __create_named_color(self, from_values(0xee, 0x82, 0xee), :Violet)
  __create_named_color(self, from_values(0xd0, 0x20, 0x90), :VioletRed)
  __create_named_color(self, from_values(0xf5, 0xde, 0xb3), :Wheat)
  __create_named_color(self, from_values(0xff, 0xff, 0xff), :White)
  __create_named_color(self, from_values(0xf5, 0xf5, 0xf5), :WhiteSmoke)
  __create_named_color(self, from_values(0xff, 0xff, 0x00), :Yellow)
  __create_named_color(self, from_values(0x9a, 0xcd, 0x32), :YellowGreen)

  # :stopdoc:
  # This namespace contains some RGB metallic colors suggested by Jim
  # Freeze.
  # :startdoc:

  module Metallic; end

  __create_named_color(Metallic, from_values(0x99, 0x99, 0x99), :Aluminum)
  __create_named_color(Metallic, from_values(0xd9, 0x87, 0x19), :CoolCopper)
  __create_named_color(Metallic, from_values(0xb8, 0x73, 0x33), :Copper)
  __create_named_color(Metallic, from_values(0x4c, 0x4c, 0x4c), :Iron)
  __create_named_color(Metallic, from_values(0x19, 0x19, 0x19), :Lead)
  __create_named_color(Metallic, from_values(0xb3, 0xb3, 0xb3), :Magnesium)
  __create_named_color(Metallic, from_values(0xe6, 0xe6, 0xe6), :Mercury)
  __create_named_color(Metallic, from_values(0x80, 0x80, 0x80), :Nickel)
  __create_named_color(Metallic, from_values(0x60, 0x00, 0x00), :PolySilicon, :Poly)
  __create_named_color(Metallic, from_values(0xcc, 0xcc, 0xcc), :Silver)
  __create_named_color(Metallic, from_values(0x66, 0x66, 0x66), :Steel)
  __create_named_color(Metallic, from_values(0x7f, 0x7f, 0x7f), :Tin)
  __create_named_color(Metallic, from_values(0x33, 0x33, 0x33), :Tungsten)
end
