require 'rake'
require 'rake/gempackagetask'
# require 'rake/rdoctask'
require 'rake/testtask'
require 'rubygems'

$:.unshift(File.dirname(__FILE__) + "/lib")
require 'color'

PKG_NAME      = 'color'
PKG_VERSION   = Color::VERSION
PKG_FILE_NAME = "#{PKG_NAME}-#{PKG_VERSION}"

RELEASE_NAME  = "REL #{PKG_VERSION}"

RUBY_FORGE_PROJECT = "color"
RUBY_FORGE_USER    = "mly"

desc "Default Task"
task :default => [ :test ]

Rake::TestTask.new do |t|
  t.test_files = FileList['test/*_test.rb']
  t.warning = true
  t.verbose = false
end

spec = Gem::Specification.new do |s|
  s.platform = Gem::Platform::RUBY
  s.name = PKG_NAME
  s.summary = "A Simply Library for Color Manipulation"
  s.description = %q{Manipulate Colors Programatically}
  s.version = PKG_VERSION
  
  s.author = "Matt Lyon"
  s.email = "matt@postsomnia.com"
  s.rubyforge_project = RUBY_FORGE_PROJECT
  s.homepage = ""
  
  s.has_rdoc = false
  s.require_path = 'lib'
  s.autorequire = 'color'
  
  s.files = [ "Rakefile", "README", "CHANGELOG", "LICENSE" ]
  s.files = s.files + Dir.glob("lib/**/*").delete_if {|item| item.include?("\.svn")}
  s.files = s.files + Dir.glob("test/**/*").delete_if {|item| item.include?("\.svn")}
end

Rake::GemPackageTask.new(spec) do |p|
  p.gem_spec = spec
  p.need_tar = true
  p.need_zip = true
end