name: Check DCO

on:
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: false

jobs:
  check-dco:
    name: Check DCO
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write # Required to write comments on the PR

    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: block
          disable-sudo: true
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            release-assets.githubusercontent.com:443

      - uses: KineticCafe/actions-dco@b8ab7a2bc910c51e9b5c01e0fc9e0ad6b739d8e0 # v3.1.1
        with:
          config: |
            comment = true
